### ISSUE TITLE
Add support for GSLB resource

### ISSUE THREAD

**Issue by cdhunt** [citrix/terraform-provider-netscaler#10]
https://github.com/chiradeep/go-nitro/tree/ed53dbb531c6a1352d9e2406dd104cf8639e8de5/config/gslb

**Comment by kschroed** [comment]
Any progress on this. Would find this very useful as many of our clients are adopting Terraform.

**Comment by chiradeep** [comment]
Please try https://github.com/citrix/terraform-provider-netscaler/releases/tag/v0.11.8-snapshot and provide feedback

**Comment by cdhunt** [comment]
I'm no longer on a team utilizing netscalers.

Ping @krushmike.

**Comment by chiradeep** [comment]
Merged PR #19
