### ISSUE TITLE
Add support for talking to MAS

### ISSUE THREAD

**Issue by hsmade** [citrix/terraform-provider-netscaler#28]
https://docs.citrix.com/en-us/netscaler-mas/12/mas-as-api-proxy-server.html

The only thing needed would be the ability to specify a value for (one of) the headers as mentioned on above page, afaics

**Comment by olljanat** [comment]
This provider is still based on version 11 of API.
So I guess that #25 will provide this one too.

**Comment by giorgos-nikolopoulos** [comment]
The following PR #30 resolves this issue.
