### ISSUE TITLE
If not present, Server not created when adding to service group with name

### ISSUE THREAD

**Issue by Priteshkal** [citrix/terraform-provider-netscaler#35]
Hi,

I tried using the latest release of the provider (v0.11.9) but here is what I noticed:

1) When I add server to the service group using IP, the provider is able to create a new server where the servername and ip are both the ip address.

2) When I try to add server to the service group using servername, the provider does not create a new server and hence its not able to bind the server to the service group unless a server with that name already exists on the netscaler.

The functionality that I was looking for in my automation was the ability to create a server with a servername and to add it to my service group on creation of my VM.

The api call that is used in the creation of the [resource](https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/10.5/configuration/basic/servicegroup_servicegroupmember_binding/servicegroup_servicegroupmember_binding/#operations) is able to create a a new server resource when an IP address is given but not if a servername is used and thereby giving an 
`error = { "errorcode": 351, "message": "No such server", "severity": "ERROR" }`

Are there some settings I am missing in my netscaler that are now allowing the provider to create a server by servername and then add it to the servicegroup?

Thanks

A continuation of Issue #26:

**Comment by giorgos-nikolopoulos** [comment]
I think this would be best resolved if we introduced a `netscaler_server` resource that will create the server and then reference the server by name in the servicegroup.

**Comment by Priteshkal** [comment]
Yeah that seems to be the case. I found some example in another provider for netscaler that might be able to give us a [headstart](https://github.com/doubret/terraform-provider-netscaler/blob/master/netscaler/resources/server.go) on what we are looking for.

**Comment by giorgos-nikolopoulos** [comment]
@Priteshkal 

Just added the netscaler_server resource to the provider.

Let us know if you have any problems with it.

**Comment by Priteshkal** [comment]
Thank you @giorgos-nikolopoulos. I'll build and test it and let you know if it works.

**Comment by Priteshkal** [comment]
This works! Thanks
