### ISSUE TITLE
 Plugin version: 2, Ours: 4

### ISSUE THREAD

**Issue by flaviotorres** [citrix/terraform-provider-netscaler#4]
Hi,

Thank you for sharing this plugin. I was wondering if I'm experiencing issues with this plugin vs my terraform latest version.

Which terraform or GO version should I use?

`2017/04/28 23:32:27 [INFO] Terraform version: 0.9.4  277bbf65d1141207dbb30485bf124b1dba08f80f
2017/04/28 23:32:27 [INFO] Go runtime version: go1.8
2017/04/28 23:32:27 [INFO] CLI args: []string{"/usr/local/bin/terraform", "plan"}`

`2017/04/28 23:32:27 [DEBUG] plugin: starting plugin: /Users/ftorre2/work/src/github.com/citrix/terraform-provider-netscaler/terraform-provider-netscaler []string{"/Users/ftorre2/work/src/github.com/citrix/terraform-provider-netscaler/terraform-provider-netscaler"}`
`2017/04/28 23:32:27 [DEBUG] plugin: waiting for RPC address for: /Users/ftorre2/work/src/github.com/citrix/terraform-provider-netscaler/terraform-provider-netscaler`
`2017/04/28 23:32:27 [DEBUG] plugin: terraform-provider-netscaler: 2017/04/28 23:32:27 [DEBUG] plugin: plugin address: unix /var/folders/cz/x88_rb0d131gwxdq013bmqp1lzn11b/T/plugin699425407
2017/04/28 23:32:27 [ERROR] root: eval: *terraform.EvalInitProvider, err: Incompatible API version with plugin. Plugin version: 2, Ours: 4
2017/04/28 23:32:27 [ERROR] root: eval: *terraform.EvalSequence, err: Incompatible API version with plugin. Plugin version: 2, Ours: 4
2017/04/28 23:32:27 [DEBUG] dag/walk: upstream errored, not walking `
`"netscaler_lbvserver.production_lb"
2017/04/28 23:32:27 [DEBUG] dag/walk: upstream errored, not walking "netscaler_servicegroup.backend"
2017/04/28 23:32:27 [DEBUG] dag/walk: upstream errored, not walking "provider.netscaler (close)"`
`Error asking for user input: 1 error(s) occurred:
provider.netscaler: Incompatible API version with plugin. Plugin version: 2, Ours: 4
2017/04/28 23:32:27 [DEBUG] plugin: waiting for all plugin processes to complete...`

**Comment by gealmei** [comment]
Hello, I got the same issue and I've changed this ./vendor/github.com/hashicorp/terraform/plugin/serve.go:22

 22         ProtocolVersion: 4,

and shows that works but I got another error 

"Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error running plan: 1 error(s) occurred:

* netscaler_lbvserver.production_lb: 1 error(s) occurred:

* netscaler_lbvserver.production_lb: gob: wrong type (map[string]string) for received field InstanceState.Meta"

**Comment by chiradeep** [comment]
The released version 4 is tested with TF v0.8.2.

**Comment by paultravers** [comment]
Latest release is v0.9.6 and requires api v4.

**Comment by chiradeep** [comment]
Please test https://github.com/citrix/terraform-provider-netscaler/releases/tag/0.96-alpha

**Comment by paultravers** [comment]
Confirmed 0.96 alpha works with Terraform v0.9.5

**Comment by chiradeep** [comment]
Fixed by da96586acd7832b5e7da589407a68172f0f896a2
