### ISSUE TITLE
Not possible to use SNI certs

### ISSUE THREAD

**Issue by hsmade** [citrix/terraform-provider-netscaler#41]
As the ssl cert binding is abstracted away, we don't have the option to use SNI certificates using https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/12.0/configuration/ssl/sslvserver_sslcertkey_binding/sslvserver_sslcertkey_binding/

**Comment by hsmade** [comment]
https://github.com/citrix/terraform-provider-netscaler/blob/master/netscaler/resource_lbvserver.go#L640

**Comment by hsmade** [comment]
https://github.com/citrix/terraform-provider-netscaler/pull/42

**Comment by giorgos-nikolopoulos** [comment]
This is fixed with #45
