### ISSUE TITLE
Binding ServiceGroup to multiple VirtualServers

### ISSUE THREAD

**Issue by sjwl** [citrix/terraform-provider-netscaler#5]
This currently doesn't seem possible.

Binding a single `netscaler_servicegroup` to multiple `netscaler_lbverver`.

**Comment by chiradeep** [comment]
What would you suggest? Should the `lbvserver` parameter be a `schema.TypeSet` instead of `schema.TypeString`?

**Comment by sjwl** [comment]
Yes that would work for us.  But was hoping the change would also consume only a single http connection.  As it is now when we have 130+ VIPs to bind to, an equal number of service groups are created which cause some calls to fail intermittently as the max number of Netscaler connections are reached.

**Comment by paultravers** [comment]
Being able to bind a single servicegroup resource to multiple vservers would also be very useful for us.

**Comment by paultravers** [comment]
Also being able to bind a service to multiple vservers would be useful, but servicegroups should suffice in the short term.

**Comment by chiradeep** [comment]
See if this works: https://github.com/citrix/terraform-provider-netscaler/releases/tag/v0.96-alpha.2 

For reducing the number of connections, we already re-use a global http.Client in the go code, which by default re-uses connections. Perhaps try and reduce the parallelism of TF 
terraform apply -parallelism=n

**Comment by paultravers** [comment]
Multiple vservers appears to be working on my test server. Thanks for the quick turnaround!

**Comment by chiradeep** [comment]
@paultravers @sjwl comments on issue #6

**Comment by sjwl** [comment]
@chiradeep Multiple vservers appear to be working on our end too.  Thank you very much!
