### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by cdhunt** [citrix/terraform-provider-netscaler#8]
Please update the Makefile to Build and Release Windows binaries.

**Comment by chiradeep** [comment]
I do not have a Windows environment handy atm. Can you test if this will work:
build_windows:
CGO_ENABLED=0 GOOS=windows godep go build -a -installsuffix cgo -ldflags '-w' -o terraform-provider-netscaler

**Comment by cdhunt** [comment]
That should work from Linux with the addition of the `.exe` extension to the name. I was able to compile both Windows and Linux binaries with that command from my Windows workstation.

**Comment by chiradeep** [comment]
Closing as it works
