### ISSUE TITLE
Implement SaveConfig() functionality

### ISSUE THREAD

**Issue by cdhunt** [citrix/terraform-provider-netscaler#9]
`client.SaveConfig()` is implemented [go-nitro ](https://github.com/chiradeep/go-nitro/blob/master/example/lbvserver.go#L62). I would prefer the SaveConfig invoked and results handled inside the provider code instead of an external shell script.

**Comment by chiradeep** [comment]
Hi, see the discussion in #6 to see why this is hard

**Comment by cdhunt** [comment]
Sorry, I add further comments to #6.
